development:
  adapter:  postgresql
  # adapter:  postgis
  encoding: unicode
  host: localhost
  postgis_extension: true
  # schema_search_path: public,postgis
  username: tron
  password: secret
  database: app_devZ
  pool: 5

test:
  adapter:  postgresql
  # adapter:  postgis
  encoding: unicode
  host: localhost
  postgis_extension: true
  # schema_search_path: public,postgis
  username: tron
  password: secret
  database: app_testZ
  pool: 5

production:
  adapter:  postgresql
  # adapter:  postgis
  encoding: unicode
  host: localhost
  postgis_extension: true
  # schema_search_path: public,postgis
  username: tron
  password: secret
  database: app_productionZ
  pool: 5